apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: clusterroles-session-rules
parameters:
- name: SPAWNER_NAMESPACE
  value: ""
  required: true
- name: SPAWNER_APPLICATION
  value: ""
  required: true
objects:
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRole
  metadata:
    labels:
      app: ${SPAWNER_APPLICATION}-${SPAWNER_NAMESPACE}
      spawner: learning-portal
    name: ${SPAWNER_APPLICATION}-${SPAWNER_NAMESPACE}-session-rules
  rules:
  - apiGroups:
    - pxc.percona.com
    resources:
    - perconaxtradbclusters
    - perconaxtradbbackups
    - perconaxtradbclusterbackups
    - perconaxtradbclusterrestores
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
