apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: configmap-session-resources
parameters:
- name: NAME_PREFIX
  value: ""
  required: false
- name: WORKSHOP_NAME
  value: ""
  required: true
- name: SPAWNER_NAMESPACE
  value: ""
  required: true
- name: SPAWNER_MODE
  value: "learning-portal"
  required: true
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${NAME_PREFIX}${WORKSHOP_NAME}-session-resources
    labels:
      app: ${NAME_PREFIX}${WORKSHOP_NAME}
      spawner: ${SPAWNER_MODE}
      class: spawner
  data:
    extra_resources.yaml: |-
      kind: List
      apiVersion: v1
      items:
      - kind: ServiceAccount
        apiVersion: v1
        metadata:
          name: percona-xtradb-cluster-operator
      - kind: Role
        apiVersion: rbac.authorization.k8s.io/v1beta1
        metadata:
          name: percona-xtradb-cluster-operator
        rules:
        - apiGroups:
          - pxc.percona.com
          resources:
          - perconaxtradbclusters
          - perconaxtradbbackups
          - perconaxtradbclusterrestores
          - perconaxtradbclusterbackups
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ''
          resources:
          - pods
          - pods/exec
          - configmaps
          - services
          - persistentvolumeclaims
          - secrets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - apps
          resources:
          - deployments
          - replicasets
          - statefulsets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - batch
          resources:
          - jobs
          - cronjobs
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
      - kind: RoleBinding
        apiVersion: rbac.authorization.k8s.io/v1beta1
        metadata:
          name: percona-xtradb-cluster-operator
        subjects:
        - kind: ServiceAccount
          name: percona-xtradb-cluster-operator
        roleRef:
          kind: Role
          name: percona-xtradb-cluster-operator
          apiGroup: rbac.authorization.k8s.io
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: percona-xtradb-cluster-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: percona-xtradb-cluster-operator
          template:
            metadata:
              labels:
                name: percona-xtradb-cluster-operator
            spec:
              serviceAccountName: percona-xtradb-cluster-operator
              containers:
              - name: percona-xtradb-cluster-operator
                image: percona/percona-xtradb-cluster-operator:1.1.0
                ports:
                - containerPort: 60000
                  name: metrics
                command:
                - percona-xtradb-cluster-operator
                imagePullPolicy: Always
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: OPERATOR_NAME
                  value: percona-xtradb-cluster-operator
      - kind: SecurityContextConstraints
        apiVersion: security.openshift.io/v1
        metadata:
          name: "${project_namespace}-wordpress-anyuid"
          labels:
            app: "${application_name}-${spawner_namespace}"
            project: "${project_namespace}"
        priority: 888
        allowedCapabilities:
        - SYS_RESOURCE
        seLinuxContext:
          type: RunAsAny
        runAsUser:
          type: RunAsAny
        users:
        - system:serviceaccount:${project_namespace}:default
