#!/bin/bash

git clone -b release-1.1.0 https://github.com/percona/percona-xtradb-cluster-operator

mv workshop /opt/app-root/workshop

# Delete all non required files from the image
rm -rf Dockerfile README.md LICENSE