#!/bin/bash

set -x

# Generate resource files from templates.
# 
# mkdir resources
# 
# oc process -f .workshop/templates/clusterroles-session-rules.yaml \
#     --param JUPYTERHUB_NAMESPACE=${JUPYTERHUB_NAMESPACE} \
#     --param JUPYTERHUB_APPLICATION=${JUPYTERHUB_APPLICATION} \
#     -o yaml > resources/clusterroles-session-rules.yaml
# 
# oc process -f .workshop/templates/clusterroles-spawner-rules.yaml \
#     --param JUPYTERHUB_NAMESPACE=${JUPYTERHUB_NAMESPACE} \
#     --param JUPYTERHUB_APPLICATION=${JUPYTERHUB_APPLICATION} \
#     -o yaml > resources/clusterroles-spawner-rules.yaml
# 
# oc process -f .workshop/templates/configmap-extra-resources.yaml \
#     --param JUPYTERHUB_NAMESPACE=${JUPYTERHUB_NAMESPACE} \
#     --param JUPYTERHUB_APPLICATION=${JUPYTERHUB_APPLICATION} \
#     -o yaml > resources/configmap-extra-resources.yaml
